name: Deploy

on: 
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Dotnet Publish
      run: dotnet publish src/WellBot.Web/WellBot.Web.csproj --configuration Release --output deploy --self-contained false --runtime linux-x64

    - name: Copy production config
      run: echo $APPSETTINGS_FILE >> deploy/appsettings.Production.json
      env:
        APPSETTINGS_FILE : ${{ secrets.APPSETTING }}

    - name: Deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.REMOTE_SSH_KEY_PASS }}
        source: ./deploy/*.*
        target: ${{ secrets.REMOTE_DIR }}
        rm: true
        debug: true

    - name: Restart Nginx
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: |
          sudo nginx -s reload
          sudo systemctl restart ${{ secrets.SERVICE_NAME }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.REMOTE_SSH_KEY_PASS }}
